version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: sql.freedb.tech
      DB_USER: freedb_brayan0621
      DB_PASSWORD: "AU!p53czm@U?5Aj"
      DB_NAME: freedb_bmmoda1
    volumes:
      - .:/var/www/html
